apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.api.name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.port }}
    name: http
  selector:
    app: {{ .Values.api.name }}
  sessionAffinity: None
  type: ClusterIP
