apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  aws.accesskey: {{ .Values.secret.aws.accessKeyID | b64enc | quote }}
  aws.secretkey: {{ .Values.secret.aws.secretAccessKey | b64enc | quote }}
  database.password: {{ .Values.secret.database.password | b64enc | quote }}
  github.key: {{ .Values.secret.github.key | b64enc | quote }}
  github.secret: {{ .Values.secret.github.secret | b64enc | quote }}
  session.secret: {{ .Values.secret.session | b64enc | quote }}
